import PrimeVue from 'primevue/config';
import Vue from "vue";
import Button from 'primevue/button';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import InputText from 'primevue/inputtext';
import OrganizationChart from 'primevue/organizationchart';
import Card from 'primevue/card';
import ScrollPanel from 'primevue/scrollpanel';
import Galleria from 'primevue/galleria';
import Carousel from 'primevue/carousel';
import Avatar from 'primevue/avatar';
import InputSwitch from 'primevue/inputswitch';
import Fieldset from 'primevue/fieldset';
import Panel from 'primevue/panel';
import Chip from 'primevue/chip';
import Divider from 'primevue/divider';

Vue.use(PrimeVue);
Vue.component('Button', Button);
Vue.component('DataTable', DataTable);
Vue.component('Column', Column);
Vue.component('ColumnGroup', ColumnGroup); 
Vue.component('InputText', InputText); 
Vue.component('OrganizationChart', OrganizationChart); 
Vue.component('Card', Card); 
Vue.component('ScrollPanel', ScrollPanel); 
Vue.component('Galleria', Galleria); 
Vue.component('Carousel', Carousel); 
Vue.component('Avatar', Avatar); 
Vue.component('InputSwitch', InputSwitch); 
Vue.component('Fieldset', Fieldset); 
Vue.component('Panel', Panel); 
Vue.component('Chip', Chip); 
Vue.component('Divider', Divider); 