import PrimeVue from 'primevue/config';
import Vue from "vue";
import Button from 'primevue/button';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import InputText from 'primevue/inputtext';
import OrganizationChart from 'primevue/organizationchart';
import Card from 'primevue/card';
import ScrollPanel from 'primevue/scrollpanel';
import Galleria from 'primevue/galleria';
import Carousel from 'primevue/carousel';
import Avatar from 'primevue/avatar';
import InputSwitch from 'primevue/inputswitch';
import Fieldset from 'primevue/fieldset';
import Panel from 'primevue/panel';
import Chip from 'primevue/chip';
import Divider from 'primevue/divider';
import Dropdown from 'primevue/dropdown';
import AutoComplete from 'primevue/autocomplete';
import Sidebar from 'primevue/sidebar';
import Timeline from 'primevue/timeline';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import ProgressBar from 'primevue/progressbar';
import Rating from 'primevue/rating';
import Tooltip from 'primevue/tooltip';

Vue.use(PrimeVue);
Vue.component('Button', Button);
Vue.component('DataTable', DataTable);
Vue.component('Column', Column);
Vue.component('ColumnGroup', ColumnGroup);
Vue.component('InputText', InputText);
Vue.component('OrganizationChart', OrganizationChart);
Vue.component('Card', Card);
Vue.component('ScrollPanel', ScrollPanel);
Vue.component('Galleria', Galleria);
Vue.component('Carousel', Carousel);
Vue.component('Avatar', Avatar);
Vue.component('InputSwitch', InputSwitch);
Vue.component('Fieldset', Fieldset);
Vue.component('Panel', Panel);
Vue.component('Chip', Chip);
Vue.component('Divider', Divider);
Vue.component('Dropdown', Dropdown);
Vue.component('AutoComplete', AutoComplete);
Vue.component('Sidebar', Sidebar); 
Vue.component('Timeline', Timeline);
Vue.component('Accordion', Accordion);
Vue.component('AccordionTab', AccordionTab);
Vue.component('TabView', TabView);
Vue.component('TabPanel', TabPanel);
Vue.component('ProgressBar', ProgressBar);
Vue.component('Rating', Rating);
Vue.component('Tooltip', Tooltip);

Vue.directive('tooltip', Tooltip);